"use client";
import type { Metadata } from "next";
import "./globals.css";
import App from "./App";
import { StyledEngineProvider, ThemeProvider } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";
import theme from "@/app/theme";
import { Toaster } from "react-hot-toast";

const metadata: Metadata = {
  title: "Paris Basketball",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StyledEngineProvider injectFirst>
      <ThemeProvider theme={theme}>
        <CssBaseline />
        <App>
          <Toaster
            toastOptions={{
              style: {
                zIndex: 9999, // Un z-index plus élevé que celui de la modal
              },
            }}
          />
          {children}{" "}
        </App>
      </ThemeProvider>
    </StyledEngineProvider>
  );
}
