"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";
import { useMenu } from "./utils/hooks/useMenu";
import { useIsScrollingUp } from "./utils/hooks/useIsScrollingUp";
import { MenuContext, ScrollingContext } from "./utils/contexts";
import LandingPage from "./components/LandingPage";
import  News  from "./components/News";
import dataNews from "./utils/data/news.json";


const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Paris Basketball",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const handleMenu = useMenu();
  const isScrolling = useIsScrollingUp();
  return (
    <MenuContext.Provider value={handleMenu}>
    <ScrollingContext.Provider value={isScrolling}>
    <html lang='fr'>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
    </ScrollingContext.Provider>
    </MenuContext.Provider>
  );
}
