name: Deploy to Hostinger

on:
  push:
    branches:
      - master  # Déclenche l'action sur les pushs vers la branche principale

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Utilisez la version de Node.js appropriée pour votre projet

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Print environment variables for debugging
        run: |
          echo "SSH_HOST: $SSH_HOST"
          echo "SSH_USERNAME: $SSH_USERNAME"
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}

      - name: Setup SSH and Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "$SSH_HOST" > ssh_host.tmp
          ssh-keyscan -H -f ssh_host.tmp >> ~/.ssh/known_hosts
          ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST exit

      - name: Deploy via rsync
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        run: |
          rsync -avz -e "ssh -i ~/.ssh/id_rsa" .next/ $SSH_USERNAME@$SSH_HOST:public_html
